project:
  type: website
  render:
    - "*.qmd"
    - "notes/**/*.qmd"
  resources:
  - assets/
website:
  title: Lemon's Website
  favicon: assets/lemon-emoji.svg
  search: false
  navbar:
    logo: assets/lemon-emoji.svg
    background: transparent
    pinned: true
    left:
    - text: Home
      href: index.qmd
    - text: About
      href: about.qmd
    - text: Notes
      href: notes.qmd
format:
  html:
    theme:
    - darkly
    - custom.scss
    include-after-body: assets/footer.html
    code-fold: true
    code-highlight: dracula
    mermaid:
      theme: dark
