project:
  type: website
  resources:
    - assets/

website:
  title: "Lemon's Website"
  search: false
  navbar:
    background: transparent
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        menu:
          - text: "Linear Algebra for Machine Learning"
            href: notes/linear-algebra.qmd
          - text: "Matrix Decompositions for Machine Learning"
            href: notes/matrix-decompositions.qmd
          - text: "Matrix Calculus for Machine Learning"
            href: notes/matrix-calculus.qmd
          - text: "Optimization for Machine Learning"
            href: notes/optimization.qmd
          - text: "Probability for Machine Learning"
            href: notes/probability.qmd
          - text: "Information Theory for Machine Learning"
            href: notes/information-theory.qmd
          - text: "Reinforcement Learning"
            href: notes/reinforcement-learning.qmd
          - text: "Probabilistic Models for Machine Learning"
            href: notes/probabilistic-ml.qmd
          - text: "Stochastic Dynamics"
            href: notes/stochastic-dynamics.qmd

format:
  html:
    theme: 
      - darkly
      - custom.scss
    code-fold: true
    code-highlight: dracula